server:
  port: 8088

wx:
  mp:
    appId: xxxxxxxxxx
    secret: xxxxxxxxxx
    token: xxxxxxxxxx
    aesKey: xxxxxxxxxx
api:
  token: xxxxxxxxxx
  send-code-keyword: 验证码
  code-template: "您正在登录 FanStars API, 验证码是: ${code}"
  code-length: 6
  code-expire-time: 300000
  width: 300
  height: 300
  margin: 1
  qrcode-scene-id: 1008
  qrcode-expire-time: 600
